name: python 
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: checkout code 
      uses: actions/checkout@v2
    - name: set-up python
      uses: actions/setup-python@v2 
      with: 
        python-version: ${{ matrix.python-version}}
    - name: install dependencies
      run: | 
        cd Chapter4 
        python -m pip install --upgrade pip 
        
    - name: run test 
      run: |
        cd Chapter4 
        python -m unittest discover

    - name: notfy us of success 
      run: echo "test passed on ${{ matrix.python-version}}"
      if : success()

     
