name: Secrets 
on:
  push:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'chose pyhton version'
        required: true
        default: '3.7'
        type: choice
        options:
          - '3.7'
          - '3.8'
          - '3.9'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: run a secret 
      run: echo "This is my secret ${{ secrets.MY_SECRETS}}"

    - name: runn an env as a secret
      run: echo "This is my secret $MY_SECRETS"
      env:
        MY_SECRETS: ${{ secrets.MY_SECRETS}}